server:
  port: 8082
spring:
  flyway:
    baselineOnMigrate: true
  application:
    name: authservice
#  main:
#    banner-mode: off
  zipkin:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=auth_db
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver






#  database:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: foo
#    password: bar
#    secret: foo
#
#server:
#  port: 8080