server:
  port: 8082
spring:
  application:
    name: auth
  flyway:
    baselineOnMigrate: true

#  main:
#    banner-mode: off
  zipkin:
    enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1/dev?currentSchema=auth_db
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

#  datasource:
#    url: jdbc:postgresql://newvision-archives.csa8xeixiy9f.us-east-1.rds.amazonaws.com/Auth?currentSchema=auth_db
#    username: postgres
#    password: Newvision1*
#    driverClassName: org.postgresql.Driver




#  database:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: foo
#    password: bar
#    secret: foo
#
#server:
#  port: 8080